### ISSUE TITLE
rainradar does not work correctly

### ISSUE THREAD

**Issue by pferdefreund** [woheller69/weather#54] opened 2022-03-15 12:40 UTC
Rainradar does not work since some days. I only see the rain and clouds but no map data. look at my screenshot and you know what i meen.
Greetings from Germany
![Screenshot_20220315-131631](https://user-images.githubusercontent.com/49428216/158379277-1613f57c-4a20-4e68-be23-64094ed37436.png)

**Comment by woheller69** [comment] 2022-03-15 14:05
I can reproduce the issue. It arises with newer webview implementations. E.g. on an older Android System Webview 88 it works well. On the same phone with Webview 99 it fails.
At the moment I have no idea why the OpenStreetMap tiles are not being loaded anymore.

**Comment by woheller69** [comment] 2022-03-15 15:21
Seems to be a bug at OpenStreetMap tiles server. I opened a bug there: gravitystorm/openstreetmap-carto#4523 
I switched to the German tiles, at least for the moment.

Can you try this?  
Remove .zip from file name and install.

[app-release.apk.zip](https://github.com/woheller69/weather/files/8254683/app-release.apk.zip)

**Comment by woheller69** [comment] 2022-03-15 17:36
Please try this instead.
After discussions with OpenStreetMaps I modified the user-agent string as requested. (Remove .zip)

[app-release.apk.zip](https://github.com/woheller69/weather/files/8255851/app-release.apk.zip)

**Comment by pferdefreund** [comment] 2022-03-15 18:16
i installed the app from here and it works fine. 
Thankyou and
Greetings from Germany

**Comment by woheller69** [comment] 2022-03-15 18:24
did you try the second version with the modified user agent?

**Comment by woheller69** [comment] 2022-03-16 08:05
Will be fixed in V5.2

**Closed** 2022-03-27 17:48 UTC
Labels: bug, Fix published
