### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [woheller69/weather#1] opened 2020-12-26 08:57 UTC
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 1.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="443" alt="bug-weather-9" src="https://user-images.githubusercontent.com/18572115/103148508-5b2b4f00-479b-11eb-9bec-c72163894603.png">

**Comment by woheller69** [comment] 2020-12-26 09:15
Thanks for report. Great to hear you like the app. On my phones I unfortunately cannot reproduce the issue. Nevertheless I will add a spacer and shift the Register button down a little in a future release.

**Comment by franklinbill** [comment] 2020-12-26 09:18
Thank you very much for your reply! Your software use process is very smooth and very good! I also hope to see better UI effect in the future

**Comment by woheller69** [comment] 2021-01-02 10:38
Fixed in V1.2

**Closed by woheller69** 2021-01-02 10:38 UTC
Labels: minor bug
